insert into scene_knowledge (
  scene_id,
  scene_name,
  unit_name,
  scene_intro,
  scene_goal,
  core_vocabulary,
  core_phrases,
  textbook_key_expressions,
  core_patterns,
  real_life_topics,
  topic_keywords,
  question_practice_patterns,
  common_errors,
  mia_followup_directions,
  scene_completion_criteria
) values (
  'unit1_job_town',
  '职业小镇',
  'Unit 1 People at work',
  'Mia 带学生逛职业小镇，认识不同职业，聊家人工作、工作地点、夜间工作和梦想职业。',
  '学生能围绕职业主题自然表达，能说出职业、询问他人职业、说明工作地点，并表达自己的梦想职业及简单原因。',
  '{"jobs":["teacher","doctor","farmer","cook","police officer","worker","scientist","bus driver","taxi driver","nurse","fireman","postman","cleaner","painter","writer","baker"],"places":["hospital","school","farm","fire station","police station","restaurant","fields","city","bus","home"],"family":["father","mother","aunt","grandpa","uncle","family member"]}'::jsonb,
  '["people at work","love our jobs","work in the fields","work at night","take people home","keep the city safe","help people","work very hard","dream job","work at a school","work in a fire station"]'::jsonb,
  '["What does he/she do?","He''s/She''s a ...","What does your father/mother/aunt do?","He/She works in/at/on ...","I want to be a ...","I want to help people.","I want to teach students Chinese.","I want to keep the city safe."]'::jsonb,
  '["What does he do?","What does she do?","What does your father do?","What does your mother do?","He''s a doctor.","She''s a teacher.","My father is a farmer.","My mother is a teacher.","He works in a hospital.","She works at a school.","I want to be a doctor."]'::jsonb,
  '["你的家人是做什么工作的？","你在哪里见过医生、老师、厨师、警察？","哪些人在晚上还要工作？他们怎样帮助大家？","你喜欢哪种职业？你想感谢哪种职业的人？","你长大后想做什么？你想怎样帮助别人？"]'::jsonb,
  '{"family_jobs":["father","mother","teacher","doctor","farmer","cook"],"work_places":["school","hospital","farm","restaurant","police station"],"helping_people":["help people","keep the city safe","teach students"],"dream_job":["I want to be ...","I want to help ...","my dream job"]}'::jsonb,
  '["引导学生问 Mia: What does he/she do?","引导学生问: What does your father/mother do?","邀请学生追问: Where does she work?"]'::jsonb,
  '["漏 a/an：He is doctor.","he/she 混用。","do/does 混用。","第三人称单数漏 s：He work in a hospital.","want 后漏 to：I want be a cook.","work in/at/on 混乱。"]'::jsonb,
  '["What does your mother/father do?","Where does he/she work?","Who works in a hospital?","Who works at night?","What do you want to be?","Why do you want to be a ...?"]'::jsonb,
  '["学生使用过至少 4 个职业词。","学生使用过至少 2 个地点词。","学生能说出 He''s/She''s a ... 或 My father/mother is a ...。","学生能说出 He/She works in/at/on ...。","学生能表达 I want to be a ...。","学生至少尝试过主动询问职业或工作地点相关问句。"]'::jsonb
)
on conflict (scene_id) do update set
  scene_name = excluded.scene_name,
  unit_name = excluded.unit_name,
  scene_intro = excluded.scene_intro,
  scene_goal = excluded.scene_goal,
  core_vocabulary = excluded.core_vocabulary,
  core_phrases = excluded.core_phrases,
  textbook_key_expressions = excluded.textbook_key_expressions,
  core_patterns = excluded.core_patterns,
  real_life_topics = excluded.real_life_topics,
  topic_keywords = excluded.topic_keywords,
  question_practice_patterns = excluded.question_practice_patterns,
  common_errors = excluded.common_errors,
  mia_followup_directions = excluded.mia_followup_directions,
  scene_completion_criteria = excluded.scene_completion_criteria;

insert into prompt_versions (
  prompt_version_id,
  prompt_key,
  prompt_name,
  prompt_type,
  version,
  status,
  model_provider,
  model,
  base_url_alias,
  model_config,
  content,
  change_goal,
  hypothesis,
  change_log,
  decision,
  activated_at
) values
(
  'pv_student_main_v1_3',
  'student_main',
  '学生端通用主 Prompt',
  'student_main',
  'v1.3',
  'Active',
  'deepseek',
  'deepseek-v4-flash',
  'deepseek_official',
  '{"temperature":0.7,"max_tokens":800,"response_format":"json_object"}'::jsonb,
  '你是 Mia，中文名“米娅”，一只会说英语、爱聊天、温柔、好奇、很会夸人的小猫。你必须根据 selected_scene、conversation_state、target_pattern 和 retrieved_knowledge 对话。只输出 JSON。',
  'MVP initial active prompt',
  'Provide stable student chat behavior.',
  'Initial version.',
  'Active for MVP',
  now()
),
(
  'pv_exit_summary_v1_1',
  'exit_summary',
  '退出总结 Prompt',
  'exit_summary',
  'v1.1',
  'Active',
  'deepseek',
  'deepseek-v4-flash',
  'deepseek_official',
  '{"temperature":0.6,"max_tokens":500,"response_format":"json_object"}'::jsonb,
  '你是 Mia。请根据本次 session 生成积极、温柔、有成就感的学生总结。只输出 JSON。',
  'MVP initial summary prompt',
  'Provide encouraging exit summary.',
  'Initial version.',
  'Active for MVP',
  now()
),
(
  'pv_judge_v1_2',
  'judge',
  '后台评测 Judge Prompt',
  'judge',
  'v1.2',
  'Active',
  'deepseek',
  'deepseek-v4-flash',
  'deepseek_official',
  '{"temperature":0.2,"max_tokens":900,"response_format":"json_object"}'::jsonb,
  '你是 MiaTalk 的 AI 产品评测员。请评估 Mia 输出质量并只输出 JSON。',
  'MVP initial judge prompt',
  'Score AI output consistently.',
  'Initial version.',
  'Active for MVP',
  now()
),
(
  'pv_bad_case_rubric_v1_0',
  'bad_case_rubric',
  'Bad Case Rubric',
  'bad_case_rubric',
  'v1.0',
  'Active',
  'deepseek',
  'not_applicable',
  'deepseek_official',
  '{}'::jsonb,
  'wrong_correction, missed_error, over_correction, grammar_too_hard, persona_break, weak_praise, weak_expression_desire, off_scene, missed_question_practice, weak_vocabulary_bridge, format_error',
  'MVP initial bad case rubric',
  'Support bad case diagnosis.',
  'Initial version.',
  'Active for MVP',
  now()
)
on conflict (prompt_version_id) do nothing;
